# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('fee', models.IntegerField()),
                ('due_date_time', models.DateTimeField(default=datetime.datetime(2017, 8, 5, 18, 43, 4, 185841, tzinfo=utc))),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('number_of_floors', models.IntegerField()),
                ('number_of_elevators', models.IntegerField()),
                ('end_of_subscription', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('fee', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=1000)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Building')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('confirmation_status', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Bill')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Janitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=60)),
                ('contract_info', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/building_and_unit_pics')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('mobile_number', models.CharField(max_length=11)),
                ('avatar', models.ImageField(upload_to='media/avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('R', 'Residential'), ('B', 'Business')], default='R', max_length=1)),
                ('area', models.IntegerField()),
                ('number_of_bedrooms', models.IntegerField(default=1)),
                ('number_of_parking_spaces', models.IntegerField(default=1)),
                ('number_of_storage_rooms', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('ownership_info', models.TextField(blank=True, max_length=1000)),
                ('rental_status', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Building')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='management.Profile')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='pictures',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Unit'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='management.Profile'),
        ),
        migrations.AddField(
            model_name='janitor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Profile'),
        ),
        migrations.AddField(
            model_name='facilityreservation',
            name='reservee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Profile'),
        ),
        migrations.AddField(
            model_name='building',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Profile'),
        ),
        migrations.AddField(
            model_name='bill',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Unit'),
        ),
    ]
