# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20170813_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='main_pic',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
