# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_building_main_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='main_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
