# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20170813_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='main_pic',
            field=models.ImageField(default='../static/building_default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
