# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20170813_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='main_pic_src',
        ),
        migrations.AddField(
            model_name='building',
            name='main_pic',
            field=models.ImageField(default='../static/building_default.png', upload_to='building_images'),
        ),
    ]
