# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20170820_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='main_pic',
            field=models.FileField(default='../static/building_default.png', upload_to='building_images'),
        ),
    ]
