# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='main_pic',
            field=models.FileField(default='../static/unit_default.png', upload_to='unit_images'),
        ),
    ]
