# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20170826_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='story',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number_of_parking_spaces',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number_of_storage_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
