# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_auto_20170827_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='main_pic',
            field=models.FileField(default='../../../static/unit_default.png', upload_to='unit_images'),
        ),
    ]
