# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_facility_main_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='cost_per_half_hour',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
