# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20170827_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onehourreserve',
            name='facility',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='cost_per_half_hour',
            new_name='cost_per_hour',
        ),
        migrations.DeleteModel(
            name='OneHourReserve',
        ),
    ]
