# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 06:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20170827_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneHourReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('reservation_status', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Facility')),
            ],
        ),
    ]
