# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_onehourreserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
