# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 08:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_building_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='number_of_residents',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
